version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: dev-requirements.txt
    - method: setuptools
      path: .
