language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - python setup.py build_ext --inplace

script:
  - pytest --cov-report term --cov=pytorchltr
  - flake8 pytorchltr tests

after_success:
  - codecov
