name: Dev Manylinux Python Wheel

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 'cp36-cp36m', 'cp37-cp37m', 'cp38-cp38' ]

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux1_x86_64

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        /opt/python/${{ matrix.python-version }}/bin/python -m pip install --upgrade pip setuptools wheel twine
        /opt/python/${{ matrix.python-version }}/bin/python -m pip install -r requirements.txt
        /opt/python/${{ matrix.python-version }}/bin/python -m pip install -r dev-requirements.txt
    - name: Build manylinux wheel
      env:
        CFLAGS: -std=c99
      run: |
        /opt/python/${{ matrix.python-version }}/bin/python setup.py build_ext
        /opt/python/${{ matrix.python-version }}/bin/pip wheel . --no-deps -w wheelhouse/
        for whl in wheelhouse/*.whl; do if auditwheel show "$whl"; then auditwheel repair "$whl" --plat "manylinux1_x86_64" -w ./dist/; fi; done
    - name: Upload wheel
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        ls dist/
        echo "twine upload dist/*"
